CREATE TABLE core.Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    UserName NVARCHAR(MAX) NOT NULL,
    Email NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    UpdatedAt DATETIME NOT NULL,
    RowVersion ROWVERSION NOT NULL
);
